server:
  port: 8080

spring:
  application:
    name: payroll-app

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true